linters:
  enable:
    - gofmt
    - golint
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unconvert
    - misspell
    - revive

run:
  deadline: 5m
  tests: true
  skip-dirs:
    - vendor

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck

linters-settings:
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false