server:
  port: ":3001"
  host: "0.0.0.0"

database:
  url: "root:root@tcp(localhost:3306)/companies_db?charset=utf8"
  ssl_mode: "disable"

kafka:
  brokers: ["localhost:9092"]
  topic: "company-events"
  group_id: "company-service"

jwt:
  secret: "your-secret-key"
  expiration: 1h